//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ToDoApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_todo_list
    {
        public int Id { get; set; }
        public Nullable<int> order { get; set; }
        public string title { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string priority { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
        public string created_by { get; set; }
    }
}
